// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/plugins/grpc/memory/proto/memory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreReq) Reset() {
	*x = StoreReq{}
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreReq) ProtoMessage() {}

func (x *StoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreReq.ProtoReflect.Descriptor instead.
func (*StoreReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescGZIP(), []int{0}
}

func (x *StoreReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StoreReq) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StoreReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type StoreResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResp) Reset() {
	*x = StoreResp{}
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResp) ProtoMessage() {}

func (x *StoreResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResp.ProtoReflect.Descriptor instead.
func (*StoreResp) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescGZIP(), []int{1}
}

func (x *StoreResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RetrieveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Filter        map[string]string      `protobuf:"bytes,4,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveReq) Reset() {
	*x = RetrieveReq{}
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveReq) ProtoMessage() {}

func (x *RetrieveReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveReq.ProtoReflect.Descriptor instead.
func (*RetrieveReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RetrieveReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RetrieveReq) GetFilter() map[string]string {
	if x != nil {
		return x.Filter
	}
	return nil
}

type RetrieveResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*MemoryResultProto   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResp) Reset() {
	*x = RetrieveResp{}
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResp) ProtoMessage() {}

func (x *RetrieveResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResp.ProtoReflect.Descriptor instead.
func (*RetrieveResp) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveResp) GetResults() []*MemoryResultProto {
	if x != nil {
		return x.Results
	}
	return nil
}

type MemoryResultProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryResultProto) Reset() {
	*x = MemoryResultProto{}
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryResultProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryResultProto) ProtoMessage() {}

func (x *MemoryResultProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryResultProto.ProtoReflect.Descriptor instead.
func (*MemoryResultProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryResultProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryResultProto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryResultProto) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MemoryResultProto) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_pkg_plugins_grpc_memory_proto_memory_proto protoreflect.FileDescriptor

const file_pkg_plugins_grpc_memory_proto_memory_proto_rawDesc = "" +
	"\n" +
	"*pkg/plugins/grpc/memory/proto/memory.proto\x12\x06memory\"\xbb\x01\n" +
	"\bStoreReq\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12:\n" +
	"\bmetadata\x18\x02 \x03(\v2\x1e.memory.StoreReq.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1b\n" +
	"\tStoreResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xcb\x01\n" +
	"\vRetrieveReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x127\n" +
	"\x06filter\x18\x04 \x03(\v2\x1f.memory.RetrieveReq.FilterEntryR\x06filter\x1a9\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\fRetrieveResp\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.memory.MemoryResultProtoR\aresults\"\xd5\x01\n" +
	"\x11MemoryResultProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12C\n" +
	"\bmetadata\x18\x04 \x03(\v2'.memory.MemoryResultProto.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012t\n" +
	"\rMemoryService\x12,\n" +
	"\x05Store\x12\x10.memory.StoreReq\x1a\x11.memory.StoreResp\x125\n" +
	"\bRetrieve\x12\x13.memory.RetrieveReq\x1a\x14.memory.RetrieveRespB8Z6github.com/mwantia/forge/pkg/plugins/grpc/memory/protob\x06proto3"

var (
	file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescOnce sync.Once
	file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescData []byte
)

func file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescGZIP() []byte {
	file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescOnce.Do(func() {
		file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_memory_proto_memory_proto_rawDesc), len(file_pkg_plugins_grpc_memory_proto_memory_proto_rawDesc)))
	})
	return file_pkg_plugins_grpc_memory_proto_memory_proto_rawDescData
}

var file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_plugins_grpc_memory_proto_memory_proto_goTypes = []any{
	(*StoreReq)(nil),          // 0: memory.StoreReq
	(*StoreResp)(nil),         // 1: memory.StoreResp
	(*RetrieveReq)(nil),       // 2: memory.RetrieveReq
	(*RetrieveResp)(nil),      // 3: memory.RetrieveResp
	(*MemoryResultProto)(nil), // 4: memory.MemoryResultProto
	nil,                       // 5: memory.StoreReq.MetadataEntry
	nil,                       // 6: memory.RetrieveReq.FilterEntry
	nil,                       // 7: memory.MemoryResultProto.MetadataEntry
}
var file_pkg_plugins_grpc_memory_proto_memory_proto_depIdxs = []int32{
	5, // 0: memory.StoreReq.metadata:type_name -> memory.StoreReq.MetadataEntry
	6, // 1: memory.RetrieveReq.filter:type_name -> memory.RetrieveReq.FilterEntry
	4, // 2: memory.RetrieveResp.results:type_name -> memory.MemoryResultProto
	7, // 3: memory.MemoryResultProto.metadata:type_name -> memory.MemoryResultProto.MetadataEntry
	0, // 4: memory.MemoryService.Store:input_type -> memory.StoreReq
	2, // 5: memory.MemoryService.Retrieve:input_type -> memory.RetrieveReq
	1, // 6: memory.MemoryService.Store:output_type -> memory.StoreResp
	3, // 7: memory.MemoryService.Retrieve:output_type -> memory.RetrieveResp
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_plugins_grpc_memory_proto_memory_proto_init() }
func file_pkg_plugins_grpc_memory_proto_memory_proto_init() {
	if File_pkg_plugins_grpc_memory_proto_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_memory_proto_memory_proto_rawDesc), len(file_pkg_plugins_grpc_memory_proto_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugins_grpc_memory_proto_memory_proto_goTypes,
		DependencyIndexes: file_pkg_plugins_grpc_memory_proto_memory_proto_depIdxs,
		MessageInfos:      file_pkg_plugins_grpc_memory_proto_memory_proto_msgTypes,
	}.Build()
	File_pkg_plugins_grpc_memory_proto_memory_proto = out.File
	file_pkg_plugins_grpc_memory_proto_memory_proto_goTypes = nil
	file_pkg_plugins_grpc_memory_proto_memory_proto_depIdxs = nil
}
