// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/plugins/proto/driver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Base lifecycle requests/responses
type NameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameRequest) Reset() {
	*x = NameRequest{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameRequest) ProtoMessage() {}

func (x *NameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameRequest.ProtoReflect.Descriptor instead.
func (*NameRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{0}
}

type NameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameResponse) Reset() {
	*x = NameResponse{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameResponse) ProtoMessage() {}

func (x *NameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameResponse.ProtoReflect.Descriptor instead.
func (*NameResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{1}
}

func (x *NameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{2}
}

type ProbeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResponse) Reset() {
	*x = ProbeResponse{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponse) ProtoMessage() {}

func (x *ProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponse.ProtoReflect.Descriptor instead.
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{3}
}

func (x *ProbeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{4}
}

type CapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  *DriverCapabilities    `protobuf:"bytes,1,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{5}
}

func (x *CapabilitiesResponse) GetCapabilities() *DriverCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{6}
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{7}
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{8}
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{9}
}

type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{11}
}

type GetPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginRequest) Reset() {
	*x = GetPluginRequest{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginRequest) ProtoMessage() {}

func (x *GetPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginRequest.ProtoReflect.Descriptor instead.
func (*GetPluginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{12}
}

type GetPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *PluginInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginResponse) Reset() {
	*x = GetPluginResponse{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginResponse) ProtoMessage() {}

func (x *GetPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginResponse.ProtoReflect.Descriptor instead.
func (*GetPluginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{13}
}

func (x *GetPluginResponse) GetInfo() *PluginInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// DriverCapabilities describes what a driver supports
type DriverCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []string               `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	Provider      *ProviderCaps          `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Memory        *MemoryCaps            `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	Channel       *ChannelCaps           `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	Tools         *ToolsCaps             `protobuf:"bytes,5,opt,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverCapabilities) Reset() {
	*x = DriverCapabilities{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverCapabilities) ProtoMessage() {}

func (x *DriverCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverCapabilities.ProtoReflect.Descriptor instead.
func (*DriverCapabilities) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{14}
}

func (x *DriverCapabilities) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *DriverCapabilities) GetProvider() *ProviderCaps {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *DriverCapabilities) GetMemory() *MemoryCaps {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *DriverCapabilities) GetChannel() *ChannelCaps {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *DriverCapabilities) GetTools() *ToolsCaps {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ProviderCaps struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SupportsStreaming bool                   `protobuf:"varint,1,opt,name=supports_streaming,json=supportsStreaming,proto3" json:"supports_streaming,omitempty"`
	SupportsVision    bool                   `protobuf:"varint,2,opt,name=supports_vision,json=supportsVision,proto3" json:"supports_vision,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProviderCaps) Reset() {
	*x = ProviderCaps{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCaps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCaps) ProtoMessage() {}

func (x *ProviderCaps) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCaps.ProtoReflect.Descriptor instead.
func (*ProviderCaps) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{15}
}

func (x *ProviderCaps) GetSupportsStreaming() bool {
	if x != nil {
		return x.SupportsStreaming
	}
	return false
}

func (x *ProviderCaps) GetSupportsVision() bool {
	if x != nil {
		return x.SupportsVision
	}
	return false
}

type MemoryCaps struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SupportsVectorSearch bool                   `protobuf:"varint,1,opt,name=supports_vector_search,json=supportsVectorSearch,proto3" json:"supports_vector_search,omitempty"`
	MaxContextSize       int32                  `protobuf:"varint,2,opt,name=max_context_size,json=maxContextSize,proto3" json:"max_context_size,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MemoryCaps) Reset() {
	*x = MemoryCaps{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryCaps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryCaps) ProtoMessage() {}

func (x *MemoryCaps) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryCaps.ProtoReflect.Descriptor instead.
func (*MemoryCaps) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{16}
}

func (x *MemoryCaps) GetSupportsVectorSearch() bool {
	if x != nil {
		return x.SupportsVectorSearch
	}
	return false
}

func (x *MemoryCaps) GetMaxContextSize() int32 {
	if x != nil {
		return x.MaxContextSize
	}
	return 0
}

type ChannelCaps struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SupportsDirectMessages bool                   `protobuf:"varint,1,opt,name=supports_direct_messages,json=supportsDirectMessages,proto3" json:"supports_direct_messages,omitempty"`
	SupportsThreads        bool                   `protobuf:"varint,2,opt,name=supports_threads,json=supportsThreads,proto3" json:"supports_threads,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ChannelCaps) Reset() {
	*x = ChannelCaps{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelCaps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCaps) ProtoMessage() {}

func (x *ChannelCaps) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCaps.ProtoReflect.Descriptor instead.
func (*ChannelCaps) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{17}
}

func (x *ChannelCaps) GetSupportsDirectMessages() bool {
	if x != nil {
		return x.SupportsDirectMessages
	}
	return false
}

func (x *ChannelCaps) GetSupportsThreads() bool {
	if x != nil {
		return x.SupportsThreads
	}
	return false
}

type ToolsCaps struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SupportsAsyncExecution bool                   `protobuf:"varint,1,opt,name=supports_async_execution,json=supportsAsyncExecution,proto3" json:"supports_async_execution,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ToolsCaps) Reset() {
	*x = ToolsCaps{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolsCaps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolsCaps) ProtoMessage() {}

func (x *ToolsCaps) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolsCaps.ProtoReflect.Descriptor instead.
func (*ToolsCaps) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{18}
}

func (x *ToolsCaps) GetSupportsAsyncExecution() bool {
	if x != nil {
		return x.SupportsAsyncExecution
	}
	return false
}

// PluginInfo describes plugin metadata
type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{19}
}

func (x *PluginInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// GenerateReq/Resp for ProviderService
type GenerateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*MessageProto        `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Temperature   float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Tools         []*ToolProto           `protobuf:"bytes,5,rep,name=tools,proto3" json:"tools,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReq) Reset() {
	*x = GenerateReq{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReq) ProtoMessage() {}

func (x *GenerateReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReq.ProtoReflect.Descriptor instead.
func (*GenerateReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{20}
}

func (x *GenerateReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateReq) GetMessages() []*MessageProto {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GenerateReq) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GenerateReq) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *GenerateReq) GetTools() []*ToolProto {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *GenerateReq) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GenerateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Usage         *UsageProto            `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResp) Reset() {
	*x = GenerateResp{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResp) ProtoMessage() {}

func (x *GenerateResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResp.ProtoReflect.Descriptor instead.
func (*GenerateResp) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{21}
}

func (x *GenerateResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GenerateResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GenerateResp) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GenerateResp) GetUsage() *UsageProto {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *GenerateResp) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type MessageProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageProto) Reset() {
	*x = MessageProto{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageProto) ProtoMessage() {}

func (x *MessageProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageProto.ProtoReflect.Descriptor instead.
func (*MessageProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{22}
}

func (x *MessageProto) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MessageProto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UsageProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageProto) Reset() {
	*x = UsageProto{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageProto) ProtoMessage() {}

func (x *UsageProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageProto.ProtoReflect.Descriptor instead.
func (*UsageProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{23}
}

func (x *UsageProto) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *UsageProto) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

type ToolProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolProto) Reset() {
	*x = ToolProto{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolProto) ProtoMessage() {}

func (x *ToolProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolProto.ProtoReflect.Descriptor instead.
func (*ToolProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{24}
}

func (x *ToolProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolProto) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// StoreReq/Resp for MemoryService
type StoreReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreReq) Reset() {
	*x = StoreReq{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreReq) ProtoMessage() {}

func (x *StoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreReq.ProtoReflect.Descriptor instead.
func (*StoreReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{25}
}

func (x *StoreReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StoreReq) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StoreReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type StoreResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResp) Reset() {
	*x = StoreResp{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResp) ProtoMessage() {}

func (x *StoreResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResp.ProtoReflect.Descriptor instead.
func (*StoreResp) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{26}
}

func (x *StoreResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RetrieveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Filter        map[string]string      `protobuf:"bytes,4,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveReq) Reset() {
	*x = RetrieveReq{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveReq) ProtoMessage() {}

func (x *RetrieveReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveReq.ProtoReflect.Descriptor instead.
func (*RetrieveReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{27}
}

func (x *RetrieveReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RetrieveReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RetrieveReq) GetFilter() map[string]string {
	if x != nil {
		return x.Filter
	}
	return nil
}

type RetrieveResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*MemoryResultProto   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResp) Reset() {
	*x = RetrieveResp{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResp) ProtoMessage() {}

func (x *RetrieveResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResp.ProtoReflect.Descriptor instead.
func (*RetrieveResp) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{28}
}

func (x *RetrieveResp) GetResults() []*MemoryResultProto {
	if x != nil {
		return x.Results
	}
	return nil
}

type MemoryResultProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryResultProto) Reset() {
	*x = MemoryResultProto{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryResultProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryResultProto) ProtoMessage() {}

func (x *MemoryResultProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryResultProto.ProtoReflect.Descriptor instead.
func (*MemoryResultProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{29}
}

func (x *MemoryResultProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryResultProto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryResultProto) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MemoryResultProto) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// SendReq/Resp for ChannelService
type SendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendReq) Reset() {
	*x = SendReq{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReq) ProtoMessage() {}

func (x *SendReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReq.ProtoReflect.Descriptor instead.
func (*SendReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{30}
}

func (x *SendReq) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SendReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendReq) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResp) Reset() {
	*x = SendResp{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResp) ProtoMessage() {}

func (x *SendResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResp.ProtoReflect.Descriptor instead.
func (*SendResp) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{31}
}

func (x *SendResp) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type ReceiveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveReq) Reset() {
	*x = ReceiveReq{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveReq) ProtoMessage() {}

func (x *ReceiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveReq.ProtoReflect.Descriptor instead.
func (*ReceiveReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{32}
}

func (x *ReceiveReq) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type MessageEvt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEvt) Reset() {
	*x = MessageEvt{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvt) ProtoMessage() {}

func (x *MessageEvt) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvt.ProtoReflect.Descriptor instead.
func (*MessageEvt) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{33}
}

func (x *MessageEvt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageEvt) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *MessageEvt) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *MessageEvt) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageEvt) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ListToolsReq/Resp and ExecuteReq/Resp for ToolsService
type ListToolsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsReq) Reset() {
	*x = ListToolsReq{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsReq) ProtoMessage() {}

func (x *ListToolsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsReq.ProtoReflect.Descriptor instead.
func (*ListToolsReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{34}
}

type ListToolsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolDefProto        `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResp) Reset() {
	*x = ListToolsResp{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResp) ProtoMessage() {}

func (x *ListToolsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResp.ProtoReflect.Descriptor instead.
func (*ListToolsResp) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{35}
}

func (x *ListToolsResp) GetTools() []*ToolDefProto {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ToolDefProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefProto) Reset() {
	*x = ToolDefProto{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefProto) ProtoMessage() {}

func (x *ToolDefProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefProto.ProtoReflect.Descriptor instead.
func (*ToolDefProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{36}
}

func (x *ToolDefProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefProto) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ExecuteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          string                 `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	Arguments     map[string]string      `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteReq) Reset() {
	*x = ExecuteReq{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteReq) ProtoMessage() {}

func (x *ExecuteReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteReq.ProtoReflect.Descriptor instead.
func (*ExecuteReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{37}
}

func (x *ExecuteReq) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ExecuteReq) GetArguments() map[string]string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type ExecuteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        map[string]string      `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsError       bool                   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResp) Reset() {
	*x = ExecuteResp{}
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResp) ProtoMessage() {}

func (x *ExecuteResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_driver_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResp.ProtoReflect.Descriptor instead.
func (*ExecuteResp) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_driver_proto_rawDescGZIP(), []int{38}
}

func (x *ExecuteResp) GetResult() map[string]string {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteResp) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

var File_pkg_plugins_proto_driver_proto protoreflect.FileDescriptor

const file_pkg_plugins_proto_driver_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/plugins/proto/driver.proto\x12\x05proto\"\r\n" +
	"\vNameRequest\"\"\n" +
	"\fNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x0e\n" +
	"\fProbeRequest\"\x1f\n" +
	"\rProbeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x15\n" +
	"\x13CapabilitiesRequest\"U\n" +
	"\x14CapabilitiesResponse\x12=\n" +
	"\fcapabilities\x18\x01 \x01(\v2\x19.proto.DriverCapabilitiesR\fcapabilities\"\r\n" +
	"\vOpenRequest\"\x0e\n" +
	"\fOpenResponse\"\x0e\n" +
	"\fCloseRequest\"\x0f\n" +
	"\rCloseResponse\"\x84\x01\n" +
	"\rConfigRequest\x128\n" +
	"\x06config\x18\x01 \x03(\v2 .proto.ConfigRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x10\n" +
	"\x0eConfigResponse\"\x12\n" +
	"\x10GetPluginRequest\":\n" +
	"\x11GetPluginResponse\x12%\n" +
	"\x04info\x18\x01 \x01(\v2\x11.proto.PluginInfoR\x04info\"\xdc\x01\n" +
	"\x12DriverCapabilities\x12\x14\n" +
	"\x05types\x18\x01 \x03(\tR\x05types\x12/\n" +
	"\bprovider\x18\x02 \x01(\v2\x13.proto.ProviderCapsR\bprovider\x12)\n" +
	"\x06memory\x18\x03 \x01(\v2\x11.proto.MemoryCapsR\x06memory\x12,\n" +
	"\achannel\x18\x04 \x01(\v2\x12.proto.ChannelCapsR\achannel\x12&\n" +
	"\x05tools\x18\x05 \x01(\v2\x10.proto.ToolsCapsR\x05tools\"f\n" +
	"\fProviderCaps\x12-\n" +
	"\x12supports_streaming\x18\x01 \x01(\bR\x11supportsStreaming\x12'\n" +
	"\x0fsupports_vision\x18\x02 \x01(\bR\x0esupportsVision\"l\n" +
	"\n" +
	"MemoryCaps\x124\n" +
	"\x16supports_vector_search\x18\x01 \x01(\bR\x14supportsVectorSearch\x12(\n" +
	"\x10max_context_size\x18\x02 \x01(\x05R\x0emaxContextSize\"r\n" +
	"\vChannelCaps\x128\n" +
	"\x18supports_direct_messages\x18\x01 \x01(\bR\x16supportsDirectMessages\x12)\n" +
	"\x10supports_threads\x18\x02 \x01(\bR\x0fsupportsThreads\"E\n" +
	"\tToolsCaps\x128\n" +
	"\x18supports_async_execution\x18\x01 \x01(\bR\x16supportsAsyncExecution\"f\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xb8\x02\n" +
	"\vGenerateReq\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12/\n" +
	"\bmessages\x18\x02 \x03(\v2\x13.proto.MessageProtoR\bmessages\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12&\n" +
	"\x05tools\x18\x05 \x03(\v2\x10.proto.ToolProtoR\x05tools\x12<\n" +
	"\bmetadata\x18\x06 \x03(\v2 .proto.GenerateReq.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x01\n" +
	"\fGenerateResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12'\n" +
	"\x05usage\x18\x04 \x01(\v2\x11.proto.UsageProtoR\x05usage\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\"<\n" +
	"\fMessageProto\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"T\n" +
	"\n" +
	"UsageProto\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\"\xc2\x01\n" +
	"\tToolProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12@\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2 .proto.ToolProto.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xba\x01\n" +
	"\bStoreReq\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x129\n" +
	"\bmetadata\x18\x02 \x03(\v2\x1d.proto.StoreReq.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1b\n" +
	"\tStoreResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xca\x01\n" +
	"\vRetrieveReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x126\n" +
	"\x06filter\x18\x04 \x03(\v2\x1e.proto.RetrieveReq.FilterEntryR\x06filter\x1a9\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\fRetrieveResp\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.proto.MemoryResultProtoR\aresults\"\xd4\x01\n" +
	"\x11MemoryResultProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12B\n" +
	"\bmetadata\x18\x04 \x03(\v2&.proto.MemoryResultProto.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\aSendReq\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x128\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1c.proto.SendReq.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\bSendResp\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"+\n" +
	"\n" +
	"ReceiveReq\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"\xec\x01\n" +
	"\n" +
	"MessageEvt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12;\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1f.proto.MessageEvt.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0e\n" +
	"\fListToolsReq\":\n" +
	"\rListToolsResp\x12)\n" +
	"\x05tools\x18\x01 \x03(\v2\x13.proto.ToolDefProtoR\x05tools\"\xc8\x01\n" +
	"\fToolDefProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12C\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2#.proto.ToolDefProto.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\n" +
	"ExecuteReq\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x12>\n" +
	"\targuments\x18\x02 \x03(\v2 .proto.ExecuteReq.ArgumentsEntryR\targuments\x1a<\n" +
	"\x0eArgumentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x01\n" +
	"\vExecuteResp\x126\n" +
	"\x06result\x18\x01 \x03(\v2\x1e.proto.ExecuteResp.ResultEntryR\x06result\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\x1a9\n" +
	"\vResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x8e\x05\n" +
	"\rDriverService\x12/\n" +
	"\x04Name\x12\x12.proto.NameRequest\x1a\x13.proto.NameResponse\x128\n" +
	"\vProbePlugin\x12\x13.proto.ProbeRequest\x1a\x14.proto.ProbeResponse\x12J\n" +
	"\x0fGetCapabilities\x12\x1a.proto.CapabilitiesRequest\x1a\x1b.proto.CapabilitiesResponse\x125\n" +
	"\n" +
	"OpenDriver\x12\x12.proto.OpenRequest\x1a\x13.proto.OpenResponse\x128\n" +
	"\vCloseDriver\x12\x13.proto.CloseRequest\x1a\x14.proto.CloseResponse\x12;\n" +
	"\fConfigDriver\x12\x14.proto.ConfigRequest\x1a\x15.proto.ConfigResponse\x12F\n" +
	"\x11GetProviderPlugin\x12\x17.proto.GetPluginRequest\x1a\x18.proto.GetPluginResponse\x12D\n" +
	"\x0fGetMemoryPlugin\x12\x17.proto.GetPluginRequest\x1a\x18.proto.GetPluginResponse\x12E\n" +
	"\x10GetChannelPlugin\x12\x17.proto.GetPluginRequest\x1a\x18.proto.GetPluginResponse\x12C\n" +
	"\x0eGetToolsPlugin\x12\x17.proto.GetPluginRequest\x1a\x18.proto.GetPluginResponse2F\n" +
	"\x0fProviderService\x123\n" +
	"\bGenerate\x12\x12.proto.GenerateReq\x1a\x13.proto.GenerateResp2p\n" +
	"\rMemoryService\x12*\n" +
	"\x05Store\x12\x0f.proto.StoreReq\x1a\x10.proto.StoreResp\x123\n" +
	"\bRetrieve\x12\x12.proto.RetrieveReq\x1a\x13.proto.RetrieveResp2l\n" +
	"\x0eChannelService\x12'\n" +
	"\x04Send\x12\x0e.proto.SendReq\x1a\x0f.proto.SendResp\x121\n" +
	"\aReceive\x12\x11.proto.ReceiveReq\x1a\x11.proto.MessageEvt0\x012s\n" +
	"\fToolsService\x121\n" +
	"\x04List\x12\x13.proto.ListToolsReq\x1a\x14.proto.ListToolsResp\x120\n" +
	"\aExecute\x12\x11.proto.ExecuteReq\x1a\x12.proto.ExecuteRespB\tZ\a./protob\x06proto3"

var (
	file_pkg_plugins_proto_driver_proto_rawDescOnce sync.Once
	file_pkg_plugins_proto_driver_proto_rawDescData []byte
)

func file_pkg_plugins_proto_driver_proto_rawDescGZIP() []byte {
	file_pkg_plugins_proto_driver_proto_rawDescOnce.Do(func() {
		file_pkg_plugins_proto_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugins_proto_driver_proto_rawDesc), len(file_pkg_plugins_proto_driver_proto_rawDesc)))
	})
	return file_pkg_plugins_proto_driver_proto_rawDescData
}

var file_pkg_plugins_proto_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 50)
var file_pkg_plugins_proto_driver_proto_goTypes = []any{
	(*NameRequest)(nil),          // 0: proto.NameRequest
	(*NameResponse)(nil),         // 1: proto.NameResponse
	(*ProbeRequest)(nil),         // 2: proto.ProbeRequest
	(*ProbeResponse)(nil),        // 3: proto.ProbeResponse
	(*CapabilitiesRequest)(nil),  // 4: proto.CapabilitiesRequest
	(*CapabilitiesResponse)(nil), // 5: proto.CapabilitiesResponse
	(*OpenRequest)(nil),          // 6: proto.OpenRequest
	(*OpenResponse)(nil),         // 7: proto.OpenResponse
	(*CloseRequest)(nil),         // 8: proto.CloseRequest
	(*CloseResponse)(nil),        // 9: proto.CloseResponse
	(*ConfigRequest)(nil),        // 10: proto.ConfigRequest
	(*ConfigResponse)(nil),       // 11: proto.ConfigResponse
	(*GetPluginRequest)(nil),     // 12: proto.GetPluginRequest
	(*GetPluginResponse)(nil),    // 13: proto.GetPluginResponse
	(*DriverCapabilities)(nil),   // 14: proto.DriverCapabilities
	(*ProviderCaps)(nil),         // 15: proto.ProviderCaps
	(*MemoryCaps)(nil),           // 16: proto.MemoryCaps
	(*ChannelCaps)(nil),          // 17: proto.ChannelCaps
	(*ToolsCaps)(nil),            // 18: proto.ToolsCaps
	(*PluginInfo)(nil),           // 19: proto.PluginInfo
	(*GenerateReq)(nil),          // 20: proto.GenerateReq
	(*GenerateResp)(nil),         // 21: proto.GenerateResp
	(*MessageProto)(nil),         // 22: proto.MessageProto
	(*UsageProto)(nil),           // 23: proto.UsageProto
	(*ToolProto)(nil),            // 24: proto.ToolProto
	(*StoreReq)(nil),             // 25: proto.StoreReq
	(*StoreResp)(nil),            // 26: proto.StoreResp
	(*RetrieveReq)(nil),          // 27: proto.RetrieveReq
	(*RetrieveResp)(nil),         // 28: proto.RetrieveResp
	(*MemoryResultProto)(nil),    // 29: proto.MemoryResultProto
	(*SendReq)(nil),              // 30: proto.SendReq
	(*SendResp)(nil),             // 31: proto.SendResp
	(*ReceiveReq)(nil),           // 32: proto.ReceiveReq
	(*MessageEvt)(nil),           // 33: proto.MessageEvt
	(*ListToolsReq)(nil),         // 34: proto.ListToolsReq
	(*ListToolsResp)(nil),        // 35: proto.ListToolsResp
	(*ToolDefProto)(nil),         // 36: proto.ToolDefProto
	(*ExecuteReq)(nil),           // 37: proto.ExecuteReq
	(*ExecuteResp)(nil),          // 38: proto.ExecuteResp
	nil,                          // 39: proto.ConfigRequest.ConfigEntry
	nil,                          // 40: proto.GenerateReq.MetadataEntry
	nil,                          // 41: proto.ToolProto.ParametersEntry
	nil,                          // 42: proto.StoreReq.MetadataEntry
	nil,                          // 43: proto.RetrieveReq.FilterEntry
	nil,                          // 44: proto.MemoryResultProto.MetadataEntry
	nil,                          // 45: proto.SendReq.MetadataEntry
	nil,                          // 46: proto.MessageEvt.MetadataEntry
	nil,                          // 47: proto.ToolDefProto.ParametersEntry
	nil,                          // 48: proto.ExecuteReq.ArgumentsEntry
	nil,                          // 49: proto.ExecuteResp.ResultEntry
}
var file_pkg_plugins_proto_driver_proto_depIdxs = []int32{
	14, // 0: proto.CapabilitiesResponse.capabilities:type_name -> proto.DriverCapabilities
	39, // 1: proto.ConfigRequest.config:type_name -> proto.ConfigRequest.ConfigEntry
	19, // 2: proto.GetPluginResponse.info:type_name -> proto.PluginInfo
	15, // 3: proto.DriverCapabilities.provider:type_name -> proto.ProviderCaps
	16, // 4: proto.DriverCapabilities.memory:type_name -> proto.MemoryCaps
	17, // 5: proto.DriverCapabilities.channel:type_name -> proto.ChannelCaps
	18, // 6: proto.DriverCapabilities.tools:type_name -> proto.ToolsCaps
	22, // 7: proto.GenerateReq.messages:type_name -> proto.MessageProto
	24, // 8: proto.GenerateReq.tools:type_name -> proto.ToolProto
	40, // 9: proto.GenerateReq.metadata:type_name -> proto.GenerateReq.MetadataEntry
	23, // 10: proto.GenerateResp.usage:type_name -> proto.UsageProto
	41, // 11: proto.ToolProto.parameters:type_name -> proto.ToolProto.ParametersEntry
	42, // 12: proto.StoreReq.metadata:type_name -> proto.StoreReq.MetadataEntry
	43, // 13: proto.RetrieveReq.filter:type_name -> proto.RetrieveReq.FilterEntry
	29, // 14: proto.RetrieveResp.results:type_name -> proto.MemoryResultProto
	44, // 15: proto.MemoryResultProto.metadata:type_name -> proto.MemoryResultProto.MetadataEntry
	45, // 16: proto.SendReq.metadata:type_name -> proto.SendReq.MetadataEntry
	46, // 17: proto.MessageEvt.metadata:type_name -> proto.MessageEvt.MetadataEntry
	36, // 18: proto.ListToolsResp.tools:type_name -> proto.ToolDefProto
	47, // 19: proto.ToolDefProto.parameters:type_name -> proto.ToolDefProto.ParametersEntry
	48, // 20: proto.ExecuteReq.arguments:type_name -> proto.ExecuteReq.ArgumentsEntry
	49, // 21: proto.ExecuteResp.result:type_name -> proto.ExecuteResp.ResultEntry
	0,  // 22: proto.DriverService.Name:input_type -> proto.NameRequest
	2,  // 23: proto.DriverService.ProbePlugin:input_type -> proto.ProbeRequest
	4,  // 24: proto.DriverService.GetCapabilities:input_type -> proto.CapabilitiesRequest
	6,  // 25: proto.DriverService.OpenDriver:input_type -> proto.OpenRequest
	8,  // 26: proto.DriverService.CloseDriver:input_type -> proto.CloseRequest
	10, // 27: proto.DriverService.ConfigDriver:input_type -> proto.ConfigRequest
	12, // 28: proto.DriverService.GetProviderPlugin:input_type -> proto.GetPluginRequest
	12, // 29: proto.DriverService.GetMemoryPlugin:input_type -> proto.GetPluginRequest
	12, // 30: proto.DriverService.GetChannelPlugin:input_type -> proto.GetPluginRequest
	12, // 31: proto.DriverService.GetToolsPlugin:input_type -> proto.GetPluginRequest
	20, // 32: proto.ProviderService.Generate:input_type -> proto.GenerateReq
	25, // 33: proto.MemoryService.Store:input_type -> proto.StoreReq
	27, // 34: proto.MemoryService.Retrieve:input_type -> proto.RetrieveReq
	30, // 35: proto.ChannelService.Send:input_type -> proto.SendReq
	32, // 36: proto.ChannelService.Receive:input_type -> proto.ReceiveReq
	34, // 37: proto.ToolsService.List:input_type -> proto.ListToolsReq
	37, // 38: proto.ToolsService.Execute:input_type -> proto.ExecuteReq
	1,  // 39: proto.DriverService.Name:output_type -> proto.NameResponse
	3,  // 40: proto.DriverService.ProbePlugin:output_type -> proto.ProbeResponse
	5,  // 41: proto.DriverService.GetCapabilities:output_type -> proto.CapabilitiesResponse
	7,  // 42: proto.DriverService.OpenDriver:output_type -> proto.OpenResponse
	9,  // 43: proto.DriverService.CloseDriver:output_type -> proto.CloseResponse
	11, // 44: proto.DriverService.ConfigDriver:output_type -> proto.ConfigResponse
	13, // 45: proto.DriverService.GetProviderPlugin:output_type -> proto.GetPluginResponse
	13, // 46: proto.DriverService.GetMemoryPlugin:output_type -> proto.GetPluginResponse
	13, // 47: proto.DriverService.GetChannelPlugin:output_type -> proto.GetPluginResponse
	13, // 48: proto.DriverService.GetToolsPlugin:output_type -> proto.GetPluginResponse
	21, // 49: proto.ProviderService.Generate:output_type -> proto.GenerateResp
	26, // 50: proto.MemoryService.Store:output_type -> proto.StoreResp
	28, // 51: proto.MemoryService.Retrieve:output_type -> proto.RetrieveResp
	31, // 52: proto.ChannelService.Send:output_type -> proto.SendResp
	33, // 53: proto.ChannelService.Receive:output_type -> proto.MessageEvt
	35, // 54: proto.ToolsService.List:output_type -> proto.ListToolsResp
	38, // 55: proto.ToolsService.Execute:output_type -> proto.ExecuteResp
	39, // [39:56] is the sub-list for method output_type
	22, // [22:39] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_pkg_plugins_proto_driver_proto_init() }
func file_pkg_plugins_proto_driver_proto_init() {
	if File_pkg_plugins_proto_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugins_proto_driver_proto_rawDesc), len(file_pkg_plugins_proto_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   50,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_pkg_plugins_proto_driver_proto_goTypes,
		DependencyIndexes: file_pkg_plugins_proto_driver_proto_depIdxs,
		MessageInfos:      file_pkg_plugins_proto_driver_proto_msgTypes,
	}.Build()
	File_pkg_plugins_proto_driver_proto = out.File
	file_pkg_plugins_proto_driver_proto_goTypes = nil
	file_pkg_plugins_proto_driver_proto_depIdxs = nil
}
