// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/plugins/grpc/provider/proto/provider.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*MessageProto        `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Temperature   float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Tools         []*ToolProto           `protobuf:"bytes,5,rep,name=tools,proto3" json:"tools,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReq) Reset() {
	*x = GenerateReq{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReq) ProtoMessage() {}

func (x *GenerateReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReq.ProtoReflect.Descriptor instead.
func (*GenerateReq) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateReq) GetMessages() []*MessageProto {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GenerateReq) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GenerateReq) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *GenerateReq) GetTools() []*ToolProto {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *GenerateReq) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GenerateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Usage         *UsageProto            `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResp) Reset() {
	*x = GenerateResp{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResp) ProtoMessage() {}

func (x *GenerateResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResp.ProtoReflect.Descriptor instead.
func (*GenerateResp) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GenerateResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GenerateResp) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GenerateResp) GetUsage() *UsageProto {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *GenerateResp) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type MessageProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageProto) Reset() {
	*x = MessageProto{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageProto) ProtoMessage() {}

func (x *MessageProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageProto.ProtoReflect.Descriptor instead.
func (*MessageProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{2}
}

func (x *MessageProto) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MessageProto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UsageProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageProto) Reset() {
	*x = UsageProto{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageProto) ProtoMessage() {}

func (x *UsageProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageProto.ProtoReflect.Descriptor instead.
func (*UsageProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{3}
}

func (x *UsageProto) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *UsageProto) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

type ToolProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolProto) Reset() {
	*x = ToolProto{}
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolProto) ProtoMessage() {}

func (x *ToolProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolProto.ProtoReflect.Descriptor instead.
func (*ToolProto) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP(), []int{4}
}

func (x *ToolProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolProto) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

var File_pkg_plugins_grpc_provider_proto_provider_proto protoreflect.FileDescriptor

const file_pkg_plugins_grpc_provider_proto_provider_proto_rawDesc = "" +
	"\n" +
	".pkg/plugins/grpc/provider/proto/provider.proto\x12\bprovider\"\xc1\x02\n" +
	"\vGenerateReq\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x122\n" +
	"\bmessages\x18\x02 \x03(\v2\x16.provider.MessageProtoR\bmessages\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12)\n" +
	"\x05tools\x18\x05 \x03(\v2\x13.provider.ToolProtoR\x05tools\x12?\n" +
	"\bmetadata\x18\x06 \x03(\v2#.provider.GenerateReq.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\fGenerateResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12*\n" +
	"\x05usage\x18\x04 \x01(\v2\x14.provider.UsageProtoR\x05usage\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\"<\n" +
	"\fMessageProto\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"T\n" +
	"\n" +
	"UsageProto\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\"\xc5\x01\n" +
	"\tToolProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12C\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2#.provider.ToolProto.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012L\n" +
	"\x0fProviderService\x129\n" +
	"\bGenerate\x12\x15.provider.GenerateReq\x1a\x16.provider.GenerateRespB:Z8github.com/mwantia/forge/pkg/plugins/grpc/provider/protob\x06proto3"

var (
	file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescOnce sync.Once
	file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescData []byte
)

func file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescGZIP() []byte {
	file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescOnce.Do(func() {
		file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_provider_proto_provider_proto_rawDesc), len(file_pkg_plugins_grpc_provider_proto_provider_proto_rawDesc)))
	})
	return file_pkg_plugins_grpc_provider_proto_provider_proto_rawDescData
}

var file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_plugins_grpc_provider_proto_provider_proto_goTypes = []any{
	(*GenerateReq)(nil),  // 0: provider.GenerateReq
	(*GenerateResp)(nil), // 1: provider.GenerateResp
	(*MessageProto)(nil), // 2: provider.MessageProto
	(*UsageProto)(nil),   // 3: provider.UsageProto
	(*ToolProto)(nil),    // 4: provider.ToolProto
	nil,                  // 5: provider.GenerateReq.MetadataEntry
	nil,                  // 6: provider.ToolProto.ParametersEntry
}
var file_pkg_plugins_grpc_provider_proto_provider_proto_depIdxs = []int32{
	2, // 0: provider.GenerateReq.messages:type_name -> provider.MessageProto
	4, // 1: provider.GenerateReq.tools:type_name -> provider.ToolProto
	5, // 2: provider.GenerateReq.metadata:type_name -> provider.GenerateReq.MetadataEntry
	3, // 3: provider.GenerateResp.usage:type_name -> provider.UsageProto
	6, // 4: provider.ToolProto.parameters:type_name -> provider.ToolProto.ParametersEntry
	0, // 5: provider.ProviderService.Generate:input_type -> provider.GenerateReq
	1, // 6: provider.ProviderService.Generate:output_type -> provider.GenerateResp
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_plugins_grpc_provider_proto_provider_proto_init() }
func file_pkg_plugins_grpc_provider_proto_provider_proto_init() {
	if File_pkg_plugins_grpc_provider_proto_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugins_grpc_provider_proto_provider_proto_rawDesc), len(file_pkg_plugins_grpc_provider_proto_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugins_grpc_provider_proto_provider_proto_goTypes,
		DependencyIndexes: file_pkg_plugins_grpc_provider_proto_provider_proto_depIdxs,
		MessageInfos:      file_pkg_plugins_grpc_provider_proto_provider_proto_msgTypes,
	}.Build()
	File_pkg_plugins_grpc_provider_proto_provider_proto = out.File
	file_pkg_plugins_grpc_provider_proto_provider_proto_goTypes = nil
	file_pkg_plugins_grpc_provider_proto_provider_proto_depIdxs = nil
}
